name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    uses: ./.github/workflows/test-pipeline.yml
    with:
      use_secrets: 'Use GitHub Secrets'
    secrets:
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
